### ISSUE TITLE
Develop Shema for Metrics

### ISSUE THREAD

**Issue by velocitatem** [IERoboticsClub/club-website#3]
[GithubRankingAction](https://github.com/velocitatem/OrgGithubRanking)

**Comment by velocitatem** [comment]
+ [ ] PR Tracking option as additional metric

**Comment by velocitatem** [comment]
Another option could be to just copy the metrics used here:

![thing](https://github-readme-stats.vercel.app/api?username=velocitatem)

And extend them by the score @i-be-keggles mentioned above

**Comment by i-be-keggles** [comment]
Adding a `dif` value to represent amount changed since update. (Contributions in past day).

**Comment by velocitatem** [comment]
Exactly what kye said but only as data returned from the API. we keep all the metrics raw in the DB

**Comment by velocitatem** [comment]
@i-be-keggles I optimized the schema:

```json
[
  {
    username: 'velocitatem',
    date: 2023-09-28T09:47:57.628Z,
    commits: 1915,
    pull_requests: 344,
    about: {
      followers: 15,
      following: 67,
      public_repos: 129,
      public_gists: 21,
      id: 60182044
    },
    stars: 65,
    cc: 300
  }
]
```

Where cc should be the number of lines changed in the past 24h. Will add to production later today.

**Comment by velocitatem** [comment]
- [ ] get rid of lines
- [ ] We get origin day + last 2 days
