### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by i-be-keggles** [IERoboticsClub/club-website#36]
Create a hamburger style menu bar for website navigation.

**Comment by velocitatem** [comment]
what if, we use a _literal_ hamburger 🍔

**Comment by velocitatem** [comment]
![Image](https://github.com/IERoboticsClub/club-website/assets/60182044/51b60c3c-c6bf-408e-b423-5275fc881c5d)

**Comment by velocitatem** [comment]
Last thing before we can close this is:
+ [ ] SVG burger and adaptive color for dark-mode
