### ISSUE TITLE
Footer for the website

### ISSUE THREAD

**Issue by velocitatem** [IERoboticsClub/club-website#62]
![Image](https://github.com/IERoboticsClub/club-website/assets/60182044/d3b2f3d7-8843-44c8-806c-a7110d54b8ea)

Rough overview of what it could look like, should have two key components:
+ Social Links
+ Resources

**Comment by velocitatem** [comment]
It would be great to combine this with #54 by putting the social links into some JSON and loading them into both components dynamically rather than hard-coding int other elements

**Comment by haxybaxy** [comment]
i can do this
