### ISSUE TITLE
Get good photos of the team

### ISSUE THREAD

**Issue by velocitatem** [IERoboticsClub/club-website#8]

**Comment by dsanmart** [comment]
I made some attempts to run Stable Diffusion img2img for this task and really does not work well XD

I have researched a little bit more about it and it seems like we will need more than just one picture if we want it to be high quality. The technique under [profilepicture.ai](https://www.profilepicture.ai/) or [photoai.com](https://photoai.com/ai-avatars) is called [DreamBooth](https://arxiv.org/pdf/2208.12242.pdf). 

This [tutorial](https://www.youtube.com/watch?v=RvPTllEv-pI) uses a notebook to apply DreamBooth on Stable Diffusion. Doing a [quick search](https://spcman.github.io/stable-diffusion-m1/using-dreambooth-on-mac/) it should be free. However, if not free, perhaps the notebook could be adapted to the mac with 64gb of M1 in the lab.

**Comment by dsanmart** [comment]
If it can be run on the Google Colab for free it would be great. We could record a video demonstration and ask everyone to train a model themselves and just share with us the weights of the finetuning or a picture in some specific style.

**Comment by velocitatem** [comment]
I also found this [colab](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_dreambooth_training.ipynb#scrollTo=If5Jswe526QP)

**Comment by velocitatem** [comment]
@dsanmart So should we do a workshop on this sometime soon?

**Comment by velocitatem** [comment]
I think its safe to close this issue at this point since we are doing the workshop this week 🎉
